language: php

php:
  - 7.0
  - 7.1
  - 7.2

# faster builds on new travis setup not using sudo
sudo: false

install:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - composer validate --strict
  - vendor/bin/codecept run